export const Types = {
    ADD_COMPANY_TO_FAVORITES: 'ADD_COMPANY_TO_FAVORITES',
    REMOVE_COMPANY_FROM_FAVORITES: 'REMOVE_COMPANY_FROM_FAVORITES',
    UPDATE_TEXT_BUBBLE: 'UPDATE_TEXT_BUBBLE',
    ADD_TEXT_BUBBLE: 'ADD_TEXT_BUBBLE',
    REMOVE_TEXT_BUBBLE: 'REMOVE_TEXT_BUBBLE',
    LOAD_TEXTS: 'LOAD_TEXTS',
};